# Generated by Django 3.0.8 on 2020-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('art', 'Art'), ('other', 'Other')], default='beauty', max_length=10),
        ),
    ]
